### PR TITLE
Simplification of the neutronWaveNumber.hpp files

### PR DESCRIPTION
**Pull request by staleyLANL**
For this PR, I've provided simplifications and consolidations of some code in the various neutronWaveNumber.hpp files. For example, the constant `5.787793139E-14` appeared multiple times before, but now appears just once.

Note: one file, `breitWigner/lvalue/Type/src/waveNumber.hpp`, wasn't `#included` anywhere. So, I removed it. If this file was slated to be used, eventually, then let me know and we can put it back in.

Compilation times appear to be somewhat variable on my computer, so I'm interested in knowing if other people do, or do not, see improved compile times with this change. I believe it's a worthwhile change to make, however, even if compile times don't improve.

### CODE REVIEW

**Comment by staleyLANL** [comment]
@jlconlin @whaeck I'm just wondering if you've had a chance to take a look at this. Maybe it'll be relevant, maybe not, given the work @whaeck has been doing, but I thought I'd ask.

**Comment by jlconlin** [comment]
I haven't looked at the code (yet). The compile time difference (for NJOY21) was negligible with this compared to the master branch. I'll look at it more closely this afternoon.

**Comment by staleyLANL** [comment]
That's unfortunate that the change didn't improve compile times. Assuming that this code is even still relevant, given the other work that's being done in the library, I think it's still a worthwhile change, as it simplifies the code and reduces redundancy.

**Review by whaeck — APPROVED** [review]
All tests pass properly so I think we're good on this one.

I did update to the latest master before compiling and running all tests.

**Pull request merged**
