### PR TITLE
Complete replacement contents for penetrationShift.hpp.

### PR DESCRIPTION
**Pull request by staleyLANL**
It seems to be indeterminate, at this point, as to whether my other current PR will, or will not, be able to work correctly with RECONR.

So, let's try this complete drop-in replacement for the old contents of penetrationShift.hpp. About half the code bulk, and for me, it took about 1/3 off the compilation time. Your mileage might vary.

I'd written this a couple of days ago, but didn't want to clutter the project with this until the old PR was accepted. With that still be undetermined at this point, I'd like to put this in, to see if it helps. Cutting *something* off of the compile times would certainly be nice.

### CODE REVIEW

**Comment by staleyLANL** [comment]
@jlconlin @whaeck Can you take a look? Github is being slow, and hasn't let me add y'all as reviewers yet.

**Comment by jlconlin** [comment]
I just tested this out. (Sorry it took awhile.) Previous to this, RECONR took 5m57s to compile [RECONR.test.cpp](https://github.com/njoy/RECONR/blob/NJOY21/integration/src/RECONR/RECONR/test/RECONR.test.cpp). With this simple change, compiling the same test took 4m7s to compile. Both of these used LLVM 10.0.0 on my MacBook Pro.

If @whaeck thinks this looks correct (I can't really tell), then let's merge this in right away. I can take advantage of this right now.

**Comment by staleyLANL** [comment]
That's good news. Feel free to try the following replacement for `channelRadius.hpp`:

```
inline auto channelRadius( const double atomicWeightRatio ){
  constexpr double amu = 1.00866491582;
  const auto scalar =
    0.123 * std::pow( amu * atomicWeightRatio, 1. / 3. ) + 0.08;
  return radius(scalar);
}
```

to see if that improves the compile time any further.

If you're like me to describe what I did with `penetrationShift.hpp`, we could do a screen share and I'll describe it.

**Comment by staleyLANL** [comment]
That's good to hear. I don't seem to have permissions to merge it, so feel free to do so if you want.

**Comment by staleyLANL** [comment]
Look good; thanks.

**Pull request merged**
