### PR TITLE
Fix/pedantisms

### PR DESCRIPTION
**Pull request by whaeck**
feature/guards should be merged first

This fixes some -Wpedantic compiler errors/warnings

### CODE REVIEW

**Comment by whaeck** [comment]
@jlconlin this is going to be easier now :-)

**Comment by jlconlin** [comment]
Precisely why I approved the Pull Request.

**Comment by jlconlin** [comment]
Well, this does a little bit, but I still get 15 warnings/errors when compiling NJOY21. See the attached file for more details.
[Warnigs.txt](https://github.com/njoy/resonanceReconstruction/files/5681370/Warnigs.txt)

**Comment by whaeck** [comment]
What are the flags you're using? I used -Werror -Wpedantic to make these corrections, like you asked. You must be using more than those flags.

**Comment by jlconlin** [comment]
> What are the flags you're using? I used -Werror -Wpedantic to make these corrections, like you asked. You must be using more than those flags.

NJOY21 uses: 
```cmake
set( common_flags "-Wall" "-Wextra" "-Wpedantic" )
set( strict_flags "-Werror" "-Wno-unknown-warning-option" )
```

**Comment by whaeck** [comment]
I used all 5 flags and fix everything that came out, but I'm not getting that last one you saw about the explicit copying of the rmatrix. I'll look at that one later - I have a meeting now.

**Review by jlconlin — APPROVED** [review]
All the compiler warnings that I've seen when compiling NJOY21 are no longer there. Thanks!

**Pull request merged**
